# Generated by Django 3.0.6 on 2020-08-09 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_posts_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='body',
            field=models.CharField(blank=True, max_length=350, null=True),
        ),
    ]
