# Generated by Django 3.0.6 on 2020-08-09 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_auto_20200809_0611'),
    ]

    operations = [
        migrations.RenameField(
            model_name='posts',
            old_name='body',
            new_name='text',
        ),
    ]
